### ISSUE TITLE
Synthetic corpus is not tokenized

### ISSUE THREAD

**Issue by noe** [rsennrich/wmt16-scripts#10]
The English-Romanian synthetic corpus referenced in the factored sample readme file ([en](http://data.statmt.org/rsennrich/wmt16_factors/en-ro/corpus.synthetic.tok.en.gz), [ro](http://data.statmt.org/rsennrich/wmt16_factors/en-ro/corpus.synthetic.tok.ro.gz)), seems not to be tokenized despite its filename suffix.

Would it be possible to rename the file or add a clarification in the readme?

**Comment by rsennrich** [comment]
thanks for reporting this. I can confirm that these two files were wrong:

- en-ro/corpus.synthetic.tok.en.gz
- en-ro/corpus.synthetic.tok.ro.gz

they have now been replaced with the correct version.
