### ISSUE TITLE
CONLL file has less sentences than text file

### ISSUE THREAD

**Issue by noe** [rsennrich/wmt16-scripts#11]
In the preprocessed files referenced at the [factored sample README file](https://github.com/rsennrich/wmt16-scripts/blob/master/factored_sample/README.md), the [CONLL file of the English-Romainan synthetic part](http://data.statmt.org/rsennrich/wmt16_factors/en-ro/corpus.synthetic.conll.en.gz) has around 20K less sentences than [the associated text file](http://data.statmt.org/rsennrich/wmt16_factors/en-ro/corpus.synthetic.tok.en.gz)

This can be verified by counting the empty lines in the CONLL file...
```
> grep '^[ \t]*$' corpus.synthetic.conll.en | wc -l
2233939
```
...and the lines in the tokenized file:
```
> wc -l < corpus.synthetic.tok.en
2253839
```

**Comment by rsennrich** [comment]
thanks for reporting this; I fixed this the same day, but apparently forgot to report the fix and close this ticket.
