### ISSUE TITLE
SGM format

### ISSUE THREAD

**Issue by masonreznov** [rsennrich/wmt16-scripts#12]
Hello @rsennrich ,

I am trying to evaluate BLEU using mteval-13a.pl. But I am using a non-sgm file format, so I am unable to wrap the file.

Any suggestions would be appreciated.

Michael

**Comment by bhaddow** [comment]
Hi Michael

You can use sacreBLEU (https://github.com/mjpost/sacreBLEU) which will give the same scores, but does not require wrapping,

best wishes
Barry

**Comment by masonreznov** [comment]
Thank you very much @bhaddow
