### ISSUE TITLE
R2L script crahses during rescoring

### ISSUE THREAD

**Issue by mehmedes** [rsennrich/wmt16-scripts#4]
When running the the r2l script for English into German the process crashes during rescoring with the followin error:

`File "/home/sariyildiznureddin/nematus/nematus/rescore.py", line 136, in <module>
    args.output, b=args.b, normalize=args.n, verbose=args.v, alignweights=args.walign)
  File "/home/sariyildiznureddin/nematus/nematus/rescore.py", line 110, in main
    rescore_model(source_file, nbest_file, saveto, models, options, b, normalize, verbose, alignweights)
  File "/home/sariyildiznureddin/nematus/nematus/rescore.py", line 72, in rescore_model
    idx = int(linesplit[0])   ##index from the source file. Starting from 0.
ValueError: invalid literal for int() with base 10: '\x1b]0;IPython: sariyildiznureddin/en-de\x070'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "r2l/rerank.py", line 21, in <module>
    num, sent, scores = line.split(' ||| ')
ValueError: need more than 1 value to unpack
`

Could you help me with this? The single model and ensemble models script work fine.

**Comment by rsennrich** [comment]
What does your input to the rescoring script look like? You need to pass both the original source (-s) and the (reversed) n-best output (-i) to the script.

**Comment by mehmedes** [comment]
Thans for your quick response!
```
# reverse
python r2l/reverse_nbest.py | \
# rescore with r2l model
THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=$device,on_unused_input=warn python $nematus/nematus/rescore.py \
      -m r2l/model-ens1.npz r2l/model-ens2.npz r2l/model-ens3.npz r2l/model-ens4.npz -s $tmpfile -b 80 -n | \
python r2l/rerank.py | \
# restore original word order
python r2l/reverse.py | \
# postprocess
sed 's/\@\@ //g' | \
$mosesdecoder/scripts/recaser/detruecase.perl | \
$mosesdecoder/scripts/tokenizer/detokenizer.perl -l $TRG
```

**Comment by mehmedes** [comment]
Now, I got it. Thanks :D
