### ISSUE TITLE
MemoryError while running train.sh script

### ISSUE THREAD

**Issue by chandreshiit** [rsennrich/wmt16-scripts#5]
Hi,

I was trying to run your train.sh script after preprocess.sh script on your sample toy data downloaded by running your script. Hoever, I got MemorryError in my machine (was running on CPU with 6 GB free space). Here is exact error and can you point me out to solve this? FYI, I had updated all the scripts to point to the correct locations of nematus and mosesdecoder.

`./train.sh
INFO: Loading data
INFO: Building model
INFO: Building sampler
INFO: Building f_init...
INFO: Done
INFO: Building f_next..
INFO: Done
INFO: Building f_log_probs...
INFO: Done
INFO: Computing gradient...
INFO: Done
INFO: Building optimizers...
INFO: Done
INFO: Total compilation time: 173.7s
INFO: Optimization
Traceback (most recent call last):
  File "config.py", line 42, in <module>
    external_validation_script='./validate.sh')
  File "build/bdist.linux-x86_64/egg/nematus/nmt.py", line 1316, in train
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
MemoryError: failed to alloc dx output
Apply node that caused the error: SoftmaxGrad(Reshape{2}.0, Softmax.0)
Toposort index: 962
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(3600, 90000), (3600, 90000)]
Inputs strides: [(360000, 4), (360000, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Reshape{3}(SoftmaxGrad.0, MakeVector{dtype='int64'}.0), Reshape{2}(SoftmaxGrad.0, MakeVector{dtype='int64'}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 967, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 967, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 967, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1108, in access_term_cache
    new_output_grads)
`

**Comment by rsennrich** [comment]
What was the configuration (network size, vocabulary size, batch size etc.) that you used? With default settings, Nematus may require more than 6GB of RAM, depending on the vocabulary size. You can try test/test_train.sh, which is a smaller model that should fit within 6GB.

**Comment by chandreshiit** [comment]
I used default configurations of nematus/nmt.py. I am actually having 16 GB of RAM.

**Comment by chandreshiit** [comment]
Hi,

FYI, I used default configurations of nematus/nmt.py. I am actually having
16 GB of RAM.

Secondly, I also tried to run WMT17 , translate-single.sh script to
translate 5 sentences from en to cs. However, it is taking more than 20
hours to translate. I downloaded the above script from
http://data.statmt.org/wmt17_systems/ and followed the instruction given
there.

Can you tell me why is this taking too long?


Thanks & Regards,

Chandresh Kumar Maurya

**Comment by rsennrich** [comment]
Hell Chandresh,

it typically only takes a few second to minutes to translate sentences with translate-single.sh. I suggest that you check your speed on Theano speed tests, and follow their recommendations for troubleshooting: http://deeplearning.net/software/theano/troubleshooting.html#slow-or-memory

Also, beware that training on CPU is too slow to be useful in practice (50-100x slower than GPU training).

best wishes,
Rico

**Comment by chandreshiit** [comment]
Hi Rico,
Sorry for the late reply.

Note that I'm not training the nematus. I am just using the translate.sh
script (pre-trained model) to translate 5 sentences from en to cs. I have
configured everything correctly. My script is running. But it takes long
time to translate and sadly I've to kill the job due to overlong.

I think using pre-trained models on CPU should not take much time. Let me
know what could be wrong.


Thanks & Regards,

Chandresh Kumar Maurya

**Comment by colorprint** [comment]
I have the same issue with long translation... it take 1-2 minutes for one short sentence on Xeon cpu, 8 cores.

**Comment by rsennrich** [comment]
There is some latency at the beginning of decoding due to model loading and the compilation of the Theano computation graph. If you need lower latency, try the server mode (server.py) with sample_client.py.

If you're having trouble with the Theano installation, you might also be interested in trying the new tensorflow branch of Nematus ( https://github.com/EdinburghNLP/nematus/tree/tensorflow ).
