### ISSUE TITLE
problem while running config.py(RuntimeWarning: Mean of empty slice.)

### ISSUE THREAD

**Issue by Blues5** [rsennrich/wmt16-scripts#6]
INFO: Reloading training progress
INFO: Loading data
INFO: Building model
INFO: Reloading model parameters
INFO: Reloading optimizer parameters
INFO: trying to load optimizer params from model/model.npz.gradinfo or model/model.npz.gradinfo.npz
INFO: Building sampler
INFO: Building f_init...
INFO: Done
INFO: Building f_next..
INFO: Done
INFO: Building f_log_probs...
INFO: Done
INFO: Computing gradient...
INFO: Done
INFO: Building optimizers...
INFO: Done
INFO: Total compilation time: 347.5s
INFO: Optimization
INFO: Seen 0 samples
/home/koeldc23/anaconda2/envs/koel/lib/python2.7/site-packages/nematus-0.2.dev0-py2.7.egg/nematus/nmt.py:1718: RuntimeWarning: Mean of empty slice.

py2.7.egg/nematus/nmt.py:1718: RuntimeWarning: Mean of empty slice.
INFO: Valid nan
nan

**Comment by rsennrich** [comment]
is your training corpus empty, or are all sentences longer than your maximum length? This could explain the line "Seen 0 samples".

**Comment by Blues5** [comment]
Thanks for the help. I'm trying to start from the scratch. After running the .download.sh file, I'm having difficulties running the .preprocess.sh

/usr/bin/env: python3: No such file or directory
/usr/bin/env: python3: No such file or directory
Tokenizer Version 1.1
Language: ro
Number of threads: 1
Tokenizer Version 1.1
Language: en
Number of threads: 1
/usr/bin/env: python3: No such file or directory
/usr/bin/env: python3: No such file or directory
Tokenizer Version 1.1
Language: ro
Number of threads: 1
Tokenizer Version 1.1
Language: en
Number of threads: 1
clean-corpus.perl: processing data/corpus.tok.ro & .en to data/corpus.tok.clean, cutoff 1-80, ratio 9

data/corpus.tok.en is too long! at /home/koeldc23/wmt16-scripts/mosesdecoder/scripts/training/clean-corpus-n.perl line 154, <E> line 1.
Traceback (most recent call last):
  File "/home/koeldc23/wmt16-scripts/subword-nmt/learn_bpe.py", line 250, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "/home/koeldc23/wmt16-scripts/subword-nmt/learn_bpe.py", line 201, in main
    threshold = max(stats.values()) / 10
ValueError: max() arg is an empty sequence


It would be worth mentioning that I tried adding export PATH=${PATH}:/usr/bin/python3 in my home directory and also adding the line #/usr/bin/python3 on top of preprocess.sh file. It is still showing the same error.

**Comment by rsennrich** [comment]
sorry, this somehow went under and is probably not of much use anymore: if "/usr/bin/env python3" doesn't work in your environment, try editing the first line in preprocess/normalise-romanian.py and preprocess/remove-diacritics.py to point to your python3 installation. The remaining errors are just because your first steps crashed.
