### ISSUE TITLE
GPU usage problem in validation script

### ISSUE THREAD

**Issue by khusainovaidar** [rsennrich/wmt16-scripts#8]
I've faced with a problem that the validation script ('translate' function) uses CPU instead of GPU, so it takes very long to finish each iteration.

Error information:
    ERROR: Could not initialize pygpu, support disabled
    Traceback:
    ...     
    packages/theano/gpuarray/__init__.py", line 65, in init_dev
    raise RuntimeError("You can't initialize the GPU in a subprocess if the parent process already did it") 

I'm using one GPU 1080. So my question is whether it is possible to run both training and validation processes on GPU, and if it is possible, what can be the problem in my case.

Thank you.

**Comment by rsennrich** [comment]
This seems to be a new check in Theano 1.0.1 ( https://github.com/Theano/Theano/commit/adf10f7dbec542ad2ad24d4c41b90643cb4e8873#diff-e8ee439d111dc77c2d361d2fe4ae8909 ).

I added a workaround to Nematus to override this check.
